#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var printHello = function () {
  console.log("hello world");
}

var printForever = function () {
  while (true){
    console.log(c.clear + c.rc() + "hello" + c.rc() + " world" + c.x);
  }
}

var printMulti = function () {
  console.log(c.clear + c.multi("hello world") + c.x);
}

var printColored = function () {
  console.log(c.rc() + "Hello World" + c.x);
}

printMulti();

