#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors");

var printHello = function (name) {
  console.log("Hello " + name);
}

var printForever = function (name) {
  while (true){
    console.log(c.clear + c.rc() + "Hello " + c.rc() + name + c.x);
  }
}

var printMulti = function (name) {
  console.log(c.clear + c.multi("Hello " + name) + c.x);
}

var printColored = function (name) {
  console.log(c.rc() + "Hello " + c.rc() + name + c.x);
}

var name = process.argv[2];

printHello(name);

