#!/usr/bin/env python3
import hello as h

if __name__ == "__main__":
    who, option = h.parse_args()
    message = 'Hello ' + who + '!'

    try:
        if option == '-m':
            h.print_colored(message)
        elif option == '-c':
            h.print_forever(message)
        else:
            h.print_boring(message)
    except KeyboardInterrupt:
        exit()


